# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

release:
  github:
    owner: didactiklabs
    name: vault-unseal-controller
  draft: false
  prerelease: auto
  mode: append
  extra_files:
    - glob: bundle.yaml
  header: |
    ## Vault Unseal Controller {{.Tag}}

    ### Installation

    ```bash
    kubectl apply -f https://github.com/didactiklabs/vault-unseal-controller/releases/download/{{.Tag}}/bundle.yaml
    ```

    ### Container Images

    - Controller: `gcr.io/didactiklabs/vault-unseal-controller:{{.Tag}}`
    - Unsealer: `gcr.io/didactiklabs/vault-unsealer:{{.Tag}}`
  footer: |
    **Full Changelog**: https://github.com/didactiklabs/vault-unseal-controller/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: 'Dependency Updates'
      regexp: "^.*build\\(deps\\):+.*$"
      order: 3
    - title: 'Other'
      order: 999
